### ISSUE TITLE
ObjectMapper is too limited

### ISSUE THREAD

**Issue by jottinger** [filelize/filelize-java#4]
In the internal ObjectMapper (Filelizer.java, line 25-ish), it'd be wiser to call `ObjectMapper.findAndRegisterModules()` instead of manually setting the `JavaTimeModule` - and it may be wise to leave the dates-as-timestamps as an option for the supplied `ObjectMapper` as well. It's convenient, but not a feature of the library.

**Comment by jansoren** [comment]
The idea behind using the objectMapper is to easily turn the java object into a human-readable format and therefore with a focus on being as convenient as possible. I have consider not exposing the objectMapper at all and just use it as a mechanism for creating the format.
